<?php

/**
 * @file
 * Blank custom module.
 *
 * Created by: Topsitemakers
 * http://www.topsitemakers.com/
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Constants.
 */
define('BOILERPLATE_SAMPLE_CONSTANT', 'sample value');

// Load the helper functions.
require_once dirname(__FILE__) . '/boilerplate.helpers.inc';

/**
 * Implements hook_help().
 */
function boilerplate_help_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'boilerplate.page':
      $build = [
        '#prefix' => '<p>',
        '#markup' => t('This is the help text for our sample page.'),
        '#suffix' => '</p>',
      ];

      return $build;
  }
}

/**
 * Implements hook_cron().
 */
function boilerplate_cron() {
  // Check if previous execution was completed.
  $lock = \Drupal::lock();
  if ($lock->acquire('boilerplate_cron')) {
    // Log a message. This is just to show that the example works.
    \Drupal::logger('boilerplate_cron')->notice('Custom cron implementation executed.');
    // Release the lock, so the next time our code can run.
    $lock->release('boilerplate_cron');
  }
}

/**
 * Implements hook_block_view_alter().
 */
function boilerplate_block_view_alter(array &$build, BlockPluginInterface $block) {
  // Here you can alter any block in the system.
}

/**
 * Implements hook_preprocess_node().
 */
function boilerplate_preprocess_node(&$variables) {
  // Alter variables passed to node templates.
  switch ($variables['node']->getType()) {
    case 'page':
      $variables['boilerplate'] = REQUEST_TIME;
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function hook_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'target_form_id':
      // Perform any form modifications here.
      break;
  }
}

/**
 * Implements hook_theme().
 */
function boilerplate_theme() {
  return [
    'boilerplate' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_entity_insert().
 */
function boilerplate_entity_insert(EntityInterface $entity) {
  drupal_register_shutdown_function('_boilerplate_post_save', $entity, 'insert');
}

/**
 * Implements hook_entity_update().
 */
function boilerplate_entity_update(EntityInterface $entity) {
  drupal_register_shutdown_function('_boilerplate_post_save', $entity, 'update');
}

/**
 * Implements hook_entity_delete
 */
function boilerplate_entity_delete(EntityInterface $entity) {
  drupal_register_shutdown_function('_boilerplate_post_save', $entity, 'delete');
}

/**
 * Post save shutdown callback.
 *
 * This has been taken from the hook_post_action module.
 *
 * @param EntityInterface $entity
 *   Updated entity.
 * @param string $op
 *   Operation name.
 */
function _boilerplate_post_save(EntityInterface $entity, $op) {
  $entity_is_saved = FALSE;
  $new_entity = NULL;

  if ($op == 'insert' || $op == 'update') {
    $entity_is_saved = TRUE;
  }
  if ($op == 'delete') {
    $new_entity = \Drupal::entityTypeManager()
      ->getStorage($entity->getEntityTypeId())
      ->load($entity->id());
    if (!$new_entity) {
      $entity_is_saved = TRUE;
    }
  }
  if ($entity_is_saved) {
    $type = $entity->getEntityTypeId();
    $module_handler = Drupal::moduleHandler();

    // Invokes hook_ENTITY_TYPE_post<operation name>.
    $module_handler->invokeAll($type . '_post' . $op, [$entity]);
    $module_handler->invokeAll($type . '_postsave', [$entity, $op]);

    // Invokes hook_entity_post<operation name>.
    $module_handler->invokeAll('entity_post' . $op, [$entity]);
    $module_handler->invokeAll('entity_postsave', [$entity, $op]);
  }
}

/**
 * Prepares variables for our boilerplate template.
 */
function template_preprocess_boilerplate(&$variables) {
  $variables['account'] = \Drupal::currentUser();
}
