<?php

/**
 * @file
 * Blank custom module.
 *
 * Created by: Topsitemakers
 * http://www.topsitemakers.com/
 */

/**
 * Constants.
 */
define('BOILERPLATE_SAMPLE_CONSTANT', 'sample value');

// Load the helper functions.
require_once dirname(__FILE__) . '/boilerplate.helpers.inc';

/**
 * Implements hook_cron().
 */
function boilerplate_cron() {
  // Check if previous execution was completed.
  $lock = \Drupal::lock();
  if ($lock->acquire('boilerplate_cron')) {
    // Log a message. This is just to show that the example works.
    \Drupal::logger('boilerplate_cron')->notice('Custom cron implementation executed.');
    // Release the lock, so the next time our code can run.
    $lock->release('boilerplate_cron');
  }
}

/**
 * Implements hook_theme().
 */
function boilerplate_theme() {
  return [
    'boilerplate' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for our boilerplate template.
 */
function template_preprocess_boilerplate(&$variables) {
  $variables['account'] = \Drupal::currentUser();
}
